### ISSUE TITLE
Search very slow / crashes

### ISSUE THREAD

**Issue by pailey** [buttercup/buttercup-mobile#247]
** Describe the issue you're having **

"Search Vaults" returns 'No entries found' for all queries

_What were you doing when the issue occurred? How do we reproduce it?_

Occurs both in app and in password autofill popup

** What OS version are you using **
_What version of Android/iOS are you using? Eg. Android 8.0 / iOS 12.3.1_

iOS 13.6.1

** What device are you using **

iPhone 7

_What phone/tablet are you running the app on?_

**Comment by houdini69** [comment]
Same issue in my case iOS 12.4.8 on a iPhone 6 Buttercup 1.15.1

**Comment by jyelland** [comment]
Also having this issue on iOS 13.7, iPhone SE, Buttercup 1.15.1.

**Comment by perry-mitchell** [comment]
Released in 1.16.0 for iOS, android pending.

**Comment by ldexterldesign** [comment]
I still experience this issue and think this issue should be reopened

Hope this helps

Sincerely

iPhone 6s
iOS 14.1
BC 1.16.0

**Comment by ldexterldesign** [comment]
[Related]?

[Related]: https://github.com/buttercup/buttercup-browser-extension/issues/368

**Comment by ldexterldesign** [comment]
BUMP

**Comment by perry-mitchell** [comment]
It's working for me on the current version. It takes a long time to return results, which I'm trying to fix in buttercup/buttercup-core#293.

For the crashing I suspect it could be a memory issue, probably linked to the same problem. I'll reopen but it's blocked by the core issue.

**Comment by ldexterldesign** [comment]
Your iPhone likely has more memory than my iPhone 6s so I imagine you may escape the crashes

Sincerely

**Comment by perry-mitchell** [comment]
Should be fixed in v2.

**Comment by ldexterldesign** [comment]
Hey Perry,

Thanks for follow up

Unfortunately, v2 still crashes for me while using search. I played around and got it to crash twice but can’t pin it to a specific interaction.

Searching and selecting maybe three or 4 entries usually will do it, never happens searching and selecting the first entry from an app start so perhaps a memory thing still..?

Hope this helps

Regards
